import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "./Navigation";
import { Theme, ThemePanel } from "@radix-ui/themes";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body >
        <Theme
          accentColor="violet"
          grayColor="sand"
          radius="large"
          scaling="105%"
        >
          <Navigation />
          <main>{children}</main>
        </Theme>
      </body>
    </html>
  );
}
